### ISSUE TITLE
energy_file = "checklines.txt"

### ISSUE THREAD

**Issue by wen1234defeng** [gautammalik-git/AutoDock-GPU-Pipeline#1]
What file is this "checklines.txt"? How did you get it?

**Comment by gautammalik-git** [comment]
Hey! I appreciate you investigating the matter. Essentially, it's a text document containing all compound names along with their binding affinities. It ought to be named 'Energy.txt' since the 'binding_energy.py' script saves the energies in that file. Thanks for catching the error. I've made the necessary updates to the 'full_dir.py' file.

**Comment by wen1234defeng** [comment]
> 嘿！感谢您调查此事。本质上，它是一个包含所有化合物名称及其绑定亲和力的文本文档。它应该命名为“Energy.txt”，因为“binding_energy.py”脚本将能量保存在该文件中。感谢您发现错误。我已经对“full_dir.py”文件进行了必要的更新。

After I changed it to Energy.txt, the extracted "full_dir" directory was empty.

**Comment by wen1234defeng** [comment]
> 嘿！感谢您调查此事。本质上，它是一个包含所有化合物名称及其绑定亲和力的文本文档。它应该命名为“Energy.txt”，因为“binding_energy.py”脚本将能量保存在该文件中。感谢您发现错误。我已经对“full_dir.py”文件进行了必要的更新。

After I changed it to Energy.txt, the extracted "full_dir" directory was empty.

**Comment by gautammalik-git** [comment]
The purpose of the _full_dir.py_ script is to duplicate the _dlg_ files of the ligands into a new directory. This allows you to extract coordinates from these files to obtain a protein-ligand complex. In the _full_dir.py_ file, there's a variable named 'dir', initially set as 'dir = lines[6:13]'. It should be adjusted to '**dir = lines[:13]**'. Alternatively, you can directly download the updated file from the repository.

**Comment by wen1234defeng** [comment]
> The purpose of the _full_dir.py_ script is to duplicate the _dlg_ files of the ligands into a new directory. This allows you to extract coordinates from these files to obtain a protein-ligand complex. In the _full_dir.py_ file, there's a variable named 'dir', initially set as 'dir = lines[6:13]'. It should be adjusted to '**dir = lines[:13]**'. Alternatively, you can directly download the updated file from the repository.

OK! Thank you very much. I have a question for you. When I was sorting out the ad_gpu docking results, I found that the small molecule was protonated, resulting in an abnormally low affinity (-30kcal/mol). This result bothers me very much, and I don’t know whether to keep it.
SMILES C=C(CNC(=O)[C@@H]1CCCC[NH2+]1)O[C@H](c1ccc(S(C)(=O)=O)cc1)[C@@H] (CF)NC(=O)C(Cl)Cl

**Comment by gautammalik-git** [comment]
You can check the protonation state using different software, just set the pH to 7.4. If the protonation makes sense biologically, then keep the molecule. Also, try docking with the uncharged version to see if the charge is affecting the result.
